# Generated by Django 3.1.5 on 2021-01-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('street_address', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('purchase_status', models.CharField(max_length=16)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=1024)),
                ('purchase_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
    ]
