# Generated by Django 3.1.5 on 2021-01-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_transaction_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uploader.customer'),
            preserve_default=False,
        ),
    ]
